/**: # Wildcard: will load the configuration params to all nodes
  ros__parameters:
    locations:
      names: ["h1", "h2", "a1", "a2", "a3", "a4", "a5", "a6"]

      pos_ne: # North-East
        # Helipads available
        h1: [0, 0]
        h2: [100, 50]
        
        # Areas to search
        a1: [20, 0]
        a2: [20, 20]
        a3: [0, 20]
        a4: [-20, 20]
        a5: [-20, 0]
        a6: [-20, -20]
      

