/**:
  ros__parameters:
    topics:
      # Possible to extend this with the different topics available
      # to make it easier to change
      cmd_land: ""

    search:
      altitude: 3.0 # Altitude above the sea
      overlap: 0.25
      area: [7.5, 7.5] 