/**:
  ros__parameters:
    topics:
      # Possible to extend this with the different topics available
      # to make it easier to change
      cmd_land: ""

    search:
      altitude: 3.0 # Altitude above the sea
      overlap: 0.25
      area: [7.5, 7.5] 

      distance: 19.0  # [m] Must be decided using a better method. Currently just hardcoded into the
                      # config file using the parameters: (3.0, 0.25, 7.5x7.5) above

    track:
      radius_of_acceptance: 0.15

      # move_method: "GNC"  # Alternatives: [GNC]
      #                     # In the future: also support for 'ANAFI'
      #                     # GNC: Relies on the guidance and velocity controller from previous thesises
      #                     # ANAFI: Uses the internal move commands of the Anafi to move. Not implemented!