/**: # Wildcard: will load the configuration params to all nodes
  ros__parameters:
    drone:
      name: "d1"

      battery_limits_per_action:
        takeoff: 25.0 # [%]
        move:    10.0 # [%] Unsure about this one, as the move could occur when moving towards the helipad
        search:  30.0 # [%]

      battery_usage_per_time_unit: # Estimated in the simulator
        track:  0.05896 # Slow movement
        move:   0.06201 # Movement speed of 3 m/s using internal commands

      velocity_limits:
        track:  0.2 # [m/s]
        move:   2.0 # [m/s] 

    locations:
      names: ["h1", "h2", "a1", "a2", "a3", "a4", "a5", "a6"] 
      paths:
        # Define which paths are available from each location
        h1: ["a1", "a3", "a5"]
        h2: ["a2"]
        a1: ["h1", a2]
        a2: ["h2", "a1", "a3"]
        a3: ["h1", "a2", "a4"]
        a4: ["a3", "a5"]
        a5: ["h1", "a4", "a6"]
        a6: ["a5"]
      recharge_available: ["h1", "h2"]  # All locations which support recharging battery
      resupply_available: ["h1", "h2"]  # All locations which support resupply of equipment
      landing_available: ["h1", "h2"]   # All locations which support landing

      pos_ne: # North-East
        # Helipads available
        h1: [0.0,   0.0]
        h2: [40.0,  40.0]
        
        # Areas to search
        a1: [20.0,  0.0]
        a2: [20.0,  20.0]
        a3: [0.0,   20.0]
        a4: [-20.0, 20.0]
        a5: [-20.0,  0.0]
        a6: [-20.0, -20.0]

      # Every position within location_radius assumed to be inside an area
      location_radius_m: 10.0 # Based on the area size in config.yaml 

    mission_init:
      start_location: "h1" # Currently defines the origin, which all locations based on (if using NED-frame)
      locations_available: ["h2", "a1" , "a2", "a3", "a4", "a5", "a6"] # Assuming no other drone nearby atm

      payload:
        num_markers: 2
        num_lifevests: 1

    mission_goals:
      locations_to_search: ["a1", "a2"] # ["a1", "a2", "a3", "a4", "a5", "a6"]
      drone_landed: false # true
      preferred_landing_location: "h1" 
      possible_landing_locations: ["h2"]  # Different from locations.landing_available, as this 
                                          # gives the locations which the drone is allowed to land based 
                                          # on the mission itself


